### ISSUE TITLE
Controllet: coordinates in a single field reduce the amount of ballons available

### ISSUE THREAD

**Issue by vitsca** [routetopa/spod#262]
When coordinates are in a single field, since the "geo" field is used two times, there are not enough fields for ballons, corresponding to the fields I would like to place.

**Comment by rended** [comment]
fixed

**Comment by vitsca** [comment]
An old datalet should be fixed as well, or not? .. In the nl-spod.routetopa.eu there is a (old) datalet that is still showing on the left.. @rended  check if it is the case to re-open it.. thanks

**Comment by vitsca** [comment]
In the databenc spod and the Regione Campania, still showing only one baloon when three fields are selected (with coordinates in one single field)
![image](https://user-images.githubusercontent.com/2544302/28521969-5a1fd5d6-7076-11e7-87ff-9cb4433aba76.png)
![image](https://user-images.githubusercontent.com/2544302/28521981-602d5142-7076-11e7-82cf-04ad1df6ff0d.png)

**Comment by andrpet** [comment]
Fixed
